### This notebook only serves to test if I can load using a JLD file

In [50]:
using HDF5
# Open the HDF5 file
file = h5open("tensor_data_2cq4A01.h5", "r");

# Access the tensor dataset
dataset = file["tensor"];

# Read the tensor data
tensor_data = read(dataset);

#### Need to add $1$ since for _DCA_utils_ numbers go from $1-21$, for our implmenetation in Python from $0-20$.

In [51]:
tensor_data = tensor_data .+ Int(1)  

97×11439 Matrix{Int64}:
 21  21  21  21  21  21  21  21  10  …  21  21  21  21  21  21  21  21  21
 21  21  21  21  21  21  21  21  16     21  21  17  21  21  21  21  21  21
 21  21  21  21  21  21  21  13   4     21  21   9  21  13  21  21  13  21
 21  21  21  21  21  21   4  16  10     21   4   4  21  15  21  21   4  21
 21  21  21  21  21  21   7  16   4     21   3  17  21   4  21  21   4  21
 21  21  21  21  21  21  13   4  21  …  21   3   3  21   4  21  21   7  21
 21  21  21  21  21  21  12  18  21     21   3   8  21  14   3  21  16  21
 21   1  21  21  21  21  15   1  14     21  12  16  21   3  12  21  13  21
 21   9  21   9  21  21  15  15  15     21   9   9  21   9  15  21  16  21
 21  15   9   9  21  17  17  15   9     21   9  17  21  17  21  16  17  21
  ⋮                   ⋮              ⋱   ⋮                   ⋮          
  3   4  21  12  21  21  21  21  21     12  21  15  21  12  21  21  21  21
 15  15  21   1  21  21  21  21  21     15  21  15  21   1  21  21  21  21
 16

In [52]:
N, M = size(tensor_data)

(97, 11439)

In [54]:
W = 1/M .* ones(M);

In [55]:
include("/home/luchinoprince/Dropbox/Old_OneDrive/Desktop/WSL_files/PlmDCA/src/PlmDCA.jl")

Main.PlmDCA

In [58]:
res = PlmDCA.plmdca_asym(tensor_data, W; lambdaJ=1e-3, lambdaH=1e-3)


site = 1	 pl = 0.1611	 time = 0.7565	exit status = FTOL_REACHED
site = 2	 pl = 0.2920	 time = 0.8840	

exit status = FTOL_REACHED


site = 3	 pl = 0.3739	 time = 0.8001	exit status = FTOL_REACHED
site = 4	 pl = 0.5593	 time = 1.1543	

exit status = FTOL_REACHED


site = 5	 pl = 0.5648	 time = 1.1465	exit status = FTOL_REACHED
site = 6	 pl = 0.7034	 time = 1.2883	

exit status = FTOL_REACHED


site = 7	 pl = 0.5759	 time = 1.2411	exit status = FTOL_REACHED
site = 8	 pl = 0.8534	 time = 1.4201	

exit status = FTOL_REACHED


site = 9	 pl = 0.7089	 time = 1.3730	exit status = FTOL_REACHED
site = 10	 pl = 0.6032	 time = 1.2432	

exit status = FTOL_REACHED


site = 11	 pl = 0.6683	 time = 1.4224	exit status = FTOL_REACHED
site = 12	 pl = 0.4119	 time = 1.0536	

exit status = FTOL_REACHED


site = 13	 pl = 0.4970	 time = 1.0725	exit status = FTOL_REACHED
site = 14	 pl = 0.4548	 time = 1.0780	

exit status = FTOL_REACHED


site = 15	 pl = 0.4387	 time = 1.1698	exit status = FTOL_REACHED
site = 16	 pl = 0.4171	 time = 1.1086	

exit status = FTOL_REACHED


site = 17	 pl = 0.8711	 time = 1.4257	exit status = FTOL_REACHED
site = 18	 pl = 1.0405	 time = 1.4677	

exit status = FTOL_REACHED


site = 19	 pl = 1.2995	 time = 1.6258	exit status = FTOL_REACHED
site = 20	 pl = 0.9054	 time = 1.3742	

exit status = FTOL_REACHED


site = 21	 pl = 1.0487	 time = 1.4116	exit status = FTOL_REACHED
site = 22	 pl = 0.8911	 time = 1.4963	

exit status = FTOL_REACHED


site = 23	 pl = 1.2879	 time = 1.5068	exit status = FTOL_REACHED
site = 24	 pl = 1.1447	 time = 1.5247	

exit status = FTOL_REACHED


site = 25	 pl = 0.4519	 time = 1.0919	exit status = FTOL_REACHED
site = 26	 pl = 1.2579	 time = 1.5512	

exit status = FTOL_REACHED


site = 27	 pl = 1.4883	 time = 1.6507	exit status = FTOL_REACHED
site = 28	 pl = 1.0062	 time = 1.6443	

exit status = FTOL_REACHED


site = 29	 pl = 0.1635	 time = 0.8264	exit status = FTOL_REACHED
site = 30	 pl = 1.2595	 time = 1.4930	

exit status = FTOL_REACHED


site = 31	 pl = 1.4130	 time = 1.7200	exit status = FTOL_REACHED
site = 32	 pl = 0.8331	 time = 1.4452	

exit status = FTOL_REACHED


site = 33	 pl = 0.1173	 time = 0.8993	exit status = FTOL_REACHED
site = 34	 pl = 1.3906	 time = 1.6542	

exit status = FTOL_REACHED


site = 35	 pl = 0.5666	 time = 1.2407	exit status = FTOL_REACHED
site = 36	 pl = 1.3904	 time = 1.7610	

exit status = FTOL_REACHED


site = 37	 pl = 0.9803	 time = 1.5120	exit status = FTOL_REACHED
site = 38	 pl = 0.7741	 time = 1.3723	

exit status = FTOL_REACHED


site = 39	 pl = 0.9801	 time = 1.6210	exit status = FTOL_REACHED
site = 40	 pl = 0.7029	 time = 1.2853	

exit status = FTOL_REACHED


site = 41	 pl = 0.7956	 time = 1.5068	exit status = FTOL_REACHED
site = 42	 pl = 1.2465	 time = 1.6058	

exit status = FTOL_REACHED


site = 43	 pl = 0.4062	 time = 1.0874	exit status = FTOL_REACHED
site = 44	 pl = 1.0616	 time = 1.4552	

exit status = FTOL_REACHED


site = 45	 pl = 1.5014	 time = 1.6667	exit status = FTOL_REACHED
site = 46	 pl = 0.5761	 time = 1.3238	

exit status = FTOL_REACHED


site = 47	 pl = 0.7561	 time = 1.3778	exit status = FTOL_REACHED
site = 48	 pl = 1.0049	 time = 1.3926	

exit status = FTOL_REACHED


site = 49	 pl = 0.6173	 time = 1.2086	exit status = FTOL_REACHED
site = 50	 pl = 0.4301	 time = 1.2898	

exit status = FTOL_REACHED


site = 51	 pl = 0.1126	 time = 0.8431	exit status = FTOL_REACHED
site = 52	 pl = 0.4253	 time = 1.0149	

exit status = FTOL_REACHED


site = 53	 pl = 0.4094	 time = 1.2578	exit status = FTOL_REACHED
site = 54	 pl = 0.2235	 time = 0.8282	

exit status = FTOL_REACHED


site = 55	 pl = 0.4648	 time = 1.0719	exit status = FTOL_REACHED
site = 56	 pl = 0.8037	 time = 1.4775	

exit status = FTOL_REACHED


site = 57	 pl = 0.3912	 time = 0.9567	exit status = FTOL_REACHED
site = 58	 pl = 1.3846	 time = 1.5515	

exit status = FTOL_REACHED


site = 59	 pl = 1.2077	 time = 1.6142	exit status = FTOL_REACHED
site = 60	 pl = 1.4505	 time = 1.8589	

exit status = FTOL_REACHED


site = 61	 pl = 1.2929	 time = 1.4323	exit status = FTOL_REACHED
site = 62	 pl = 1.0324	 time = 1.5654	

exit status = FTOL_REACHED


site = 63	 pl = 0.5669	 time = 1.2288	exit status = FTOL_REACHED
site = 64	 pl = 1.4440	 time = 1.6837	

exit status = FTOL_REACHED


site = 65	 pl = 1.2915	 time = 1.6480	exit status = FTOL_REACHED
site = 66	 pl = 0.3572	 time = 1.0177	

exit status = FTOL_REACHED


site = 67	 pl = 0.9509	 time = 1.4819	exit status = FTOL_REACHED
site = 68	 pl = 1.3143	 time = 1.6181	

exit status = FTOL_REACHED


site = 69	 pl = 0.9779	 time = 1.4562	exit status = FTOL_REACHED
site = 70	 pl = 0.9988	 time = 1.4931	

exit status = FTOL_REACHED


site = 71	 pl = 0.9252	 time = 1.4715	exit status = FTOL_REACHED
site = 72	 pl = 1.1632	 time = 1.6646	

exit status = FTOL_REACHED


site = 73	 pl = 1.4103	 time = 1.6324	exit status = FTOL_REACHED
site = 74	 pl = 0.8541	 time = 1.5145	

exit status = FTOL_REACHED


site = 75	 pl = 1.1211	 time = 1.5696	exit status = FTOL_REACHED
site = 76	 pl = 0.5192	 time = 1.0888	

exit status = FTOL_REACHED


site = 77	 pl = 0.5027	 time = 1.1425	exit status = FTOL_REACHED
site = 78	 pl = 1.3247	 time = 1.7404	

exit status = FTOL_REACHED


site = 79	 pl = 0.6676	 time = 1.2871	exit status = FTOL_REACHED
site = 80	 pl = 0.8889	 time = 1.4419	

exit status = FTOL_REACHED


site = 81	 pl = 0.4593	 time = 1.1650	exit status = FTOL_REACHED
site = 82	 pl = 0.8019	 time = 1.4637	

exit status = FTOL_REACHED


site = 83	 pl = 1.0171	 time = 1.5960	exit status = FTOL_REACHED
site = 84	 pl = 0.5649	 time = 1.0470	

exit status = FTOL_REACHED


site = 85	 pl = 1.0490	 time = 1.5307	exit status = FTOL_REACHED
site = 86	 pl = 0.8761	 time = 1.3663	

exit status = FTOL_REACHED


site = 87	 pl = 0.8512	 time = 1.4584	exit status = FTOL_REACHED
site = 88	 pl = 0.8547	 time = 1.4456	

exit status = FTOL_REACHED


site = 89	 pl = 0.8381	 time = 1.4533	exit status = FTOL_REACHED
site = 90	 pl = 0.6368	 time = 1.2174	

exit status = FTOL_REACHED


site = 91	 pl = 0.7776	 time = 1.3368	exit status = FTOL_REACHED
site = 92	 pl = 0.6570	 time = 1.2080	

exit status = FTOL_REACHED


site = 93	 pl = 0.4811	 time = 1.1142	exit status = FTOL_REACHED
site = 94	 pl = 0.4241	 time = 1.0428	

exit status = FTOL_REACHED


site = 95	 pl = 0.4705	 time = 1.1303	exit status = FTOL_REACHED
site = 96	 pl = 0.3829	 time = 1.0282	

exit status = FTOL_REACHED


site = 97	 pl = 0.0949	 time = 0.5811	exit status = FTOL_REACHED


Interestingly, this statistical consistency remains valid if the SP LM (i) are minimized independently. While
this allows for a parallel and efficient implementation, it leads for finite data to asymmetric couplings $J_{ij} (a, b) \neq J_{ji} (b, a)$. In practice, we infer each coupling as the mean of the asymmetric estimates $[J_{ij}(a,b)+J_{ji}(b,a)]/2$. Extract from paper [Inverse Statistical Physics of Protein Sequences](https://arxiv.org/pdf/1703.01222.pdf). This explains the output of the plmDCA output!

In [8]:
#sum(res.pslike)/N

In [19]:
#length(res.score)

1653

Their vocabilary is [dict][https://github.com/pagnani/ArDCA.jl/blob/master/python-notebook/arDCA_sklearn.ipynb]:
def letter2number(a): 
    #to convert the amino acids letters into integer numbers from 0 to 20
    switcher = {
        '-': 20,
        'A': 0,
        'C': 1,
        'D':2,
        'E':3,
        'F':4,
        'G':5,
        'H':6,
        'I':7,
        'K':8,
        'L':9,
        'M':10,
        'N':11,
        'P':12,
        'Q':13,
        'R':14,
        'S':15,
        'T':16,
        'V':17,
        'W':18,
        'Y':19,     
    }
    return switcher.get(a,0)

## Let us now try to train the ARDCA model

In [37]:
using ArDCA

In [94]:
arnet, arvar = ardca(tensor_data, W; lambdaJ=1e-4, lambdaH=1e-4, permorder=:NATURAL)

site = 2	pl = 0.5864	time = 0.0662	status = FTOL_REACHED
site = 3	pl = 0.7720	time = 0.0980	status = FTOL_REACHED


site = 4	pl = 0.9178	time = 0.1231	status = FTOL_REACHED
site = 5	pl = 1.0208	time = 0.1210	

status = FTOL_REACHED


site = 6	pl = 1.1460	time = 0.1392	status = FTOL_REACHED
site = 7	pl = 0.9862	time = 0.1795	

status = FTOL_REACHED


site = 8	pl = 1.3223	time = 0.1911	status = FTOL_REACHED
site = 9	pl = 1.1926	time = 0.1990	

status = FTOL_REACHED


site = 10	pl = 1.2027	time = 0.2292	status = FTOL_REACHED
site = 11	pl = 1.1412	time = 0.2231	

status = FTOL_REACHED


site = 12	pl = 0.7859	time = 0.2361	status = FTOL_REACHED
site = 13	pl = 0.6962	time = 0.2551	

status = FTOL_REACHED


site = 14	pl = 0.8227	time = 0.2984	status = FTOL_REACHED
site = 15	pl = 0.8410	time = 0.3206	

status = FTOL_REACHED


site = 16	pl = 0.6437	time = 0.3036	status = FTOL_REACHED
site = 17	pl = 1.3551	time = 0.3975	

status = FTOL_REACHED


site = 18	pl = 1.5760	time = 0.4388	status = FTOL_REACHED
site = 19	pl = 1.7094	time = 0.4324	

status = FTOL_REACHED


site = 20	pl = 1.2070	time = 0.4203	status = FTOL_REACHED
site = 21	pl = 1.3700	time = 0.4692	

status = FTOL_REACHED


site = 22	pl = 1.2232	time = 0.4782	status = FTOL_REACHED
site = 23	pl = 1.5610	time = 0.5429	

status = FTOL_REACHED


site = 24	pl = 1.4128	time = 0.5264	status = FTOL_REACHED
site = 25	pl = 0.5775	time = 0.4514	

status = FTOL_REACHED


site = 26	pl = 1.5107	time = 0.5831	status = FTOL_REACHED
site = 27	pl = 1.6866	time = 0.6091	

status = FTOL_REACHED


site = 28	pl = 1.2983	time = 0.6297	status = FTOL_REACHED
site = 29	pl = 0.1734	time = 0.3499	

status = FTOL_REACHED


site = 30	pl = 1.3851	time = 0.6823	status = FTOL_REACHED
site = 31	pl = 1.5893	time = 0.6518	

status = FTOL_REACHED


site = 32	pl = 0.9707	time = 0.7117	status = FTOL_REACHED
site = 33	pl = 0.1005	time = 0.3537	

status = FTOL_REACHED


site = 34	pl = 1.5662	time = 0.7857	status = FTOL_REACHED
site = 35	pl = 0.6479	time = 0.6651	

status = FTOL_REACHED


site = 36	pl = 1.5161	time = 0.8465	status = FTOL_REACHED
site = 37	pl = 1.0774	time = 0.7962	

status = FTOL_REACHED


site = 38	pl = 0.8478	time = 0.7439	status = FTOL_REACHED
site = 39	pl = 1.0172	time = 0.9804	

status = FTOL_REACHED


site = 40	pl = 0.7317	time = 0.7165	status = FTOL_REACHED
site = 41	pl = 0.8348	time = 0.8046	

status = FTOL_REACHED


site = 42	pl = 1.2301	time = 1.0064	status = FTOL_REACHED
site = 43	pl = 0.3863	time = 0.6981	

status = FTOL_REACHED


site = 44	pl = 1.0344	time = 1.0898	status = FTOL_REACHED
site = 45	pl = 1.4354	time = 1.3108	

status = FTOL_REACHED


site = 46	pl = 0.5176	time = 0.8878	status = FTOL_REACHED
site = 47	pl = 0.6809	time = 0.8854	

status = FTOL_REACHED


site = 48	pl = 0.8957	time = 1.1902	status = FTOL_REACHED
site = 49	pl = 0.4926	time = 1.0557	

status = FTOL_REACHED


site = 50	pl = 0.4057	time = 0.8380	status = FTOL_REACHED
site = 51	pl = 0.0642	time = 0.4994	

status = FTOL_REACHED


site = 52	pl = 0.3581	time = 1.1436	status = FTOL_REACHED
site = 53	pl = 0.3793	time = 1.0314	

status = FTOL_REACHED


site = 54	pl = 0.1792	time = 0.6832	status = FTOL_REACHED
site = 55	pl = 0.4205	time = 0.8564	

status = FTOL_REACHED


site = 56	pl = 0.6346	time = 1.5756	status = FTOL_REACHED
site = 57	pl = 0.3613	time = 1.0488	

status = FTOL_REACHED


site = 58	pl = 1.2311	time = 1.9835	status = FTOL_REACHED
site = 59	pl = 1.1456	time = 1.7613	

status = FTOL_REACHED


site = 60	pl = 1.2869	time = 2.0364	status = FTOL_REACHED
site = 61	pl = 1.1441	time = 1.8483	

status = FTOL_REACHED


site = 62	pl = 0.8473	time = 1.9046	status = FTOL_REACHED
site = 63	pl = 0.4286	time = 1.3951	

status = FTOL_REACHED


site = 64	pl = 1.2434	time = 2.2756	status = FTOL_REACHED
site = 65	pl = 1.0862	time = 2.1669	

status = FTOL_REACHED


site = 66	pl = 0.2528	time = 1.0642	status = FTOL_REACHED
site = 67	pl = 0.7849	time = 2.1153	

status = FTOL_REACHED


site = 68	pl = 1.0942	time = 2.4476	status = FTOL_REACHED
site = 69	pl = 0.7594	time = 2.0476	

status = FTOL_REACHED


site = 70	pl = 0.7996	time = 2.3820	status = FTOL_REACHED
site = 71	pl = 0.6935	time = 2.0641	

status = FTOL_REACHED


site = 72	pl = 0.8712	time = 2.5596	status = FTOL_REACHED
site = 73	pl = 1.1077	time = 2.7282	

status = FTOL_REACHED


site = 74	pl = 0.6992	time = 2.1274	status = FTOL_REACHED
site = 75	pl = 0.7881	time = 2.6715	

status = FTOL_REACHED


site = 76	pl = 0.3433	time = 1.6094	status = FTOL_REACHED
site = 77	pl = 0.3109	time = 1.5989	

status = FTOL_REACHED


site = 78	pl = 0.9753	time = 3.0969	status = FTOL_REACHED
site = 79	pl = 0.5044	time = 2.0659	

status = FTOL_REACHED


site = 80	pl = 0.6025	time = 2.6684	status = FTOL_REACHED
site = 81	pl = 0.3002	time = 1.6773	

status = FTOL_REACHED


site = 82	pl = 0.5570	time = 2.4112	status = FTOL_REACHED
site = 83	pl = 0.6328	time = 2.9579	

status = FTOL_REACHED


site = 84	pl = 0.3510	time = 1.9862	status = FTOL_REACHED
site = 85	pl = 0.7531	time = 3.0021	

status = FTOL_REACHED


site = 86	pl = 0.6116	time = 2.8017	status = FTOL_REACHED
site = 87	pl = 0.6094	time = 2.9170	

status = FTOL_REACHED


site = 88	pl = 0.6325	time = 2.9541	status = FTOL_REACHED
site = 89	pl = 0.5940	time = 2.9734	

status = FTOL_REACHED


site = 90	pl = 0.4077	time = 2.4383	status = FTOL_REACHED
site = 91	pl = 0.5201	time = 2.9328	

status = FTOL_REACHED


site = 92	pl = 0.4144	time = 2.7320	status = FTOL_REACHED
site = 93	pl = 0.2935	time = 2.2898	

status = FTOL_REACHED


site = 94	pl = 0.2830	time = 2.1448	status = FTOL_REACHED
site = 95	pl = 0.2742	time = 2.1978	

status = FTOL_REACHED


site = 96	pl = 0.2010	time = 2.0406	status = FTOL_REACHED
site = 97	pl = 0.0446	time = 0.9804	

status = FTOL_REACHED


(ArNet [N=97 q=21], ArVar [N=97 M=11439 q=21 λJ = 0.0001 λH = 0.0001 Z::Int64])

In [85]:
M = 1_0000;
generated_alignment = sample(arnet,M);     


In [86]:
minimum(generated_alignment)

1

In [87]:
generated_alignment = generated_alignment .- 1;

In [62]:
generated_alignment[24, begin:end]

10000-element Vector{Int64}:
  2
  5
 11
  2
  2
  2
 13
  2
  2
  6
  ⋮
  3
  8
  2
  2
  2
  2
  3
 16
  5

In [88]:
using PyCall

In [89]:
np=pyimport("numpy");
samples_ardca=np.asarray(generated_alignment);
np.save("samples_ardca.npy", samples_ardca);

In [80]:
arnet.J[3]

21×21×3 Array{Float64, 3}:
[:, :, 1] =
 -0.00242729  -0.0103762  -0.000870773  …  -0.000189567  -0.0314534
 -0.00242729  -0.0103762  -0.000870773     -0.000189567  -0.0314534
 -0.00242729  -0.0103762  -0.000870773     -0.000189567  -0.0314534
 -0.00242729  -0.0103762  -0.000870773     -0.000189567  -0.0314534
 -0.00242729  -0.0103762  -0.000870773     -0.000189567  -0.0314534
 -0.00242729  -0.0103762  -0.000870773  …  -0.000189567  -0.0314534
 -0.00242729  -0.0103762  -0.000870773     -0.000189567  -0.0314534
 -0.0431509    0.0711189  -0.0238232        0.35645       0.122824
 -0.00242729  -0.0103762  -0.000870773     -0.000189567  -0.0314534
 -0.206584     0.125732   -0.133621        -0.0317878     1.01531
  ⋮                                     ⋱                 ⋮
 -0.00242729  -0.0103762  -0.000870773     -0.000189567  -0.0314534
 -0.00242729  -0.0103762  -0.000870773     -0.000189567  -0.0314534
 -0.00242729  -0.0103762  -0.000870773     -0.000189567  -0.0314534
 -0.00242729  -0.010

In [95]:
arnet.p0

21-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.006031995803829006
 0.0
 0.050179211469533636
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.005682314887665006
 0.0
 0.0
 0.896144767899154

In [97]:
using Distributions

In [102]:
?Distributions.wsample

ErrorException: syntax: invalid identifier name "?"

In [2]:
m = 10
w = 1/m*ones(1,m)

1×10 Matrix{Float64}:
 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1

In [4]:
for i in eachindex(w)
    println(i)
end


1
2
3
4
5
6
7
8
9
10


$p_0$ of the library is the marginal of the first position! We have to pass it to the function!